// api/transcript.js
// Vercel Serverless Function：輸入 YouTube 影片連結，回傳純文字逐字稿。
//
// 原理：YouTube 沒有對外開放的「下載逐字稿」API，但影片頁面的原始碼裡
// 會內嵌字幕檔（caption tracks）的網址。這支函式在伺服器端（不受瀏覽器
// CORS限制）抓取影片頁面、解析出字幕網址，再把字幕XML轉成純文字回傳。
//
// 注意：這是非官方做法，依賴YouTube目前的頁面結構，如果YouTube改版，
// 這支函式可能需要跟著調整。且僅對「有上字幕（不論自動或人工）」的
// 影片有效，完全沒有字幕的影片會回傳 404 錯誤。

export default async function handler(req, res) {
  // 允許前端網頁跨網域呼叫這支API
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  const { url } = req.query;
  if (!url) {
    return res.status(400).json({ error: '缺少 url 參數，請提供 YouTube 影片連結。' });
  }

  const videoId = extractYouTubeId(url);
  if (!videoId) {
    return res.status(400).json({ error: '無法從這個連結辨識出YouTube影片ID，請確認連結格式。' });
  }

  try {
    // 1. 抓取影片觀看頁面（用一般瀏覽器的 User-Agent，並帶上CONSENT cookie避免被導去Cookie同意頁）
    const pageRes = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36',
        'Accept-Language': 'zh-TW,zh;q=0.9,en;q=0.8',
        'Cookie': 'CONSENT=YES+1'
      }
    });

    if (!pageRes.ok) {
      return res.status(502).json({ error: `無法連線到YouTube（狀態碼 ${pageRes.status}），請稍後再試。` });
    }
    const html = await pageRes.text();

    if (html.includes('action="https://consent.youtube.com')) {
      return res.status(502).json({ error: '請求被YouTube的Cookie同意頁擋下，請稍後再試一次。' });
    }

    // 2. 用更穩定的方式取出字幕資訊：切在 "captions": 這個key之後，再切到下一個已知的key為止
    const splitted = html.split('"captions":');
    if (splitted.length < 2) {
      const hasPlayerResponse = html.includes('ytInitialPlayerResponse');
      const playabilityMatch = html.match(/"playabilityStatus":\s*\{[^}]*?"status":"([^"]+)"/);
      const reasonMatch = html.match(/"reason":"([^"]+)"/);
      const debugInfo = req.query.debug ? {
        htmlLength: html.length,
        hasPlayerResponse,
        playabilityStatus: playabilityMatch ? playabilityMatch[1] : null,
        reason: reasonMatch ? reasonMatch[1] : null,
        htmlSnippet: html.slice(0, 300)
      } : undefined;
      return res.status(404).json({
        error: hasPlayerResponse
          ? '這部影片沒有偵測到可用的字幕（可能沒有上字幕，或是私人/受限影片，也可能是Vercel的伺服器IP被YouTube判定為機器人，回傳了簡化版頁面）。'
          : '無法讀取到影片資料，可能暫時被YouTube擋下，請稍後再試一次。',
        debug: debugInfo
      });
    }

    let captionsJson;
    try {
      const raw = splitted[1].split(',"videoDetails')[0].replace(/\n/g, '');
      captionsJson = JSON.parse(raw);
    } catch (e) {
      return res.status(500).json({ error: '解析字幕資訊失敗，YouTube頁面結構可能有變動，請通知開發者更新。' });
    }

    const tracks = captionsJson?.playerCaptionsTracklistRenderer?.captionTracks;
    if (!tracks || tracks.length === 0) {
      return res.status(404).json({ error: '這部影片沒有可用的字幕。' });
    }

    // 3. 選字幕語言：優先中文，其次英文，否則第一個可用的
    const track =
      tracks.find(t => (t.languageCode || '').startsWith('zh')) ||
      tracks.find(t => (t.languageCode || '').startsWith('en')) ||
      tracks[0];

    if (!track || !track.baseUrl) {
      return res.status(404).json({ error: '找不到可用的字幕檔連結。' });
    }

    // 4. 抓取字幕檔內容（XML格式），並清乾淨HTML轉義字元
    const capRes = await fetch(track.baseUrl);
    if (!capRes.ok) {
      return res.status(502).json({ error: '抓取字幕檔內容失敗，請稍後再試。' });
    }
    const xml = await capRes.text();

    const transcript = xml
      .replace(/<text[^>]*>/g, '')
      .replace(/<\/text>/g, '\n')
      .replace(/&amp;/g, '&')
      .replace(/&#39;/g, "'")
      .replace(/&quot;/g, '"')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/\n{2,}/g, '\n')
      .trim();

    if (!transcript) {
      return res.status(404).json({ error: '字幕檔是空的，這部影片可能沒有實際字幕內容。' });
    }

    return res.status(200).json({
      videoId,
      language: track.languageCode || '未知',
      isAutoGenerated: track.kind === 'asr',
      transcript
    });
  } catch (err) {
    console.error('transcript fetch error:', err);
    return res.status(500).json({ error: '伺服器處理時發生錯誤，請稍後再試。' });
  }
}

function extractYouTubeId(url) {
  const patterns = [
    /(?:youtube\.com\/watch\?v=)([^&]+)/,
    /(?:youtu\.be\/)([^?&]+)/,
    /(?:youtube\.com\/shorts\/)([^?&]+)/,
    /(?:youtube\.com\/embed\/)([^?&]+)/,
  ];
  for (const p of patterns) {
    const m = url.match(p);
    if (m) return m[1];
  }
  return null;
}
